/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;


import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.Vehiculo;

/**
 *
 * @author jonat
 */
public class DlgGestionDeClientes extends javax.swing.JDialog {

    private ArrayList<Vehiculo> listaVeh;
    private DefaultTableModel model;
    /**
     * Creates new form DlgMainVehiculos
     */
    public DlgGestionDeClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public DlgGestionDeClientes(java.awt.Frame parent, boolean modal,
            ArrayList<Vehiculo> listaVeh) {
        super(parent, modal);
        initComponents();
        this.listaVeh = listaVeh;
    }

    public ArrayList<Vehiculo> getListaVeh() {
        return listaVeh;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMostrarClientes = new javax.swing.JLabel();
        txtMostrarCliente = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        lblCantVehiculos = new javax.swing.JLabel();
        txtCantVehiculos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Vehículos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblMostrarClientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMostrarClientes.setText("Mostrar cliente");

        txtMostrarCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMostrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMostrarClienteActionPerformed(evt);
            }
        });
        txtMostrarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMostrarClienteKeyReleased(evt);
            }
        });

        btnInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar.png"))); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblMostrarClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMostrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMostrarClientes)
                    .addComponent(txtMostrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblClientes);

        lblCantVehiculos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCantVehiculos.setText("Cant. de clientes registrados:");

        txtCantVehiculos.setEditable(false);
        txtCantVehiculos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCantVehiculos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantVehiculos)
                    .addComponent(txtCantVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        JFrame padre = (JFrame) this.getOwner();
       
        DlgNewVehiculo winNew = new DlgNewVehiculo(padre, true,listaVeh, 1);
        winNew.setTitle("Agregar Vehículo");
        winNew.setVisible(true);
        this.listaVeh = winNew.getListaVeh();
        muestraTabla();
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        muestraTabla();
    }//GEN-LAST:event_formWindowActivated

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (tblClientes.getSelectedRowCount() == 1){
            int resp = JOptionPane.showConfirmDialog(this, "¿Desea borrar el vehículo seleccionado?");
            
            if (resp == 0){  //El usuario desea borrar
                int index = tblClientes.getSelectedRow();
                
                listaVeh.remove(index);
                JOptionPane.showMessageDialog(this, "Vehículo eliminado");
            }      
        }else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar un vehículo");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtMostrarClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMostrarClienteKeyReleased
        String titulo[] = {"Placa", "Marca", "Modelo", "Transmición",
            "Cilindraje", "Fecha Compra"};
        Vehiculo veh;

        model = new DefaultTableModel(null, titulo);
        for (int i = 0; i < listaVeh.size(); i++) {
            
            veh = listaVeh.get(i);
            if (veh.getPlaca().toLowerCase().contains(txtMostrarCliente.getText().toLowerCase())
                    || veh.getMarca().toLowerCase().contains(txtMostrarCliente.getText().toLowerCase())
                    || veh.getModelo().toLowerCase().contains(txtMostrarCliente.getText().toLowerCase())) {
                Object row[] = {listaVeh.get(i).getPlaca(),
                    listaVeh.get(i).getMarca(),
                    listaVeh.get(i).getModelo(),
                    listaVeh.get(i).getTransmision(),
                    listaVeh.get(i).getCilindraje(),
                    listaVeh.get(i).getFechaCompra()};
                model.addRow(row);
            }
        }

        tblClientes.setModel(model);
        txtCantVehiculos.setText(String.valueOf(tblClientes.getRowCount()));
    }//GEN-LAST:event_txtMostrarClienteKeyReleased

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (tblClientes.getSelectedRowCount() == 1) {
            int index = tblClientes.getSelectedRow();
             Vehiculo veh = new Vehiculo();
             
             veh.setPlaca(tblClientes.getValueAt(index, 0).toString());
             veh.setMarca(tblClientes.getValueAt(index, 1).toString());
             veh.setModelo(tblClientes.getValueAt(index, 2).toString());
             veh.setTransmision(tblClientes.getValueAt(index, 3).toString());
             veh.setCilindraje(Integer.parseInt(
                     tblClientes.getValueAt(index, 4).toString()));
             LocalDate fecha = LocalDate.parse(tblClientes.getValueAt(index, 5).toString());
             
             veh.setFechaCompra(fecha);
            JFrame padre = (JFrame) this.getOwner();
             DlgNewVehiculo winEdit = new DlgNewVehiculo(padre, true, listaVeh, 2, veh, 
                     index);
             winEdit.setLocationRelativeTo(null);
             winEdit.setTitle("Editar Vehículo");
             winEdit.setVisible(true);
             this.listaVeh = winEdit.getListaVeh();
             
        } else {
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar un único registro");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtMostrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMostrarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMostrarClienteActionPerformed

    private void muestraTabla() {
        String titulo[] = {"Cedula", "Nombre", "FechaNac", "Genero", 
            "telefono", "Direccion"};

        model = new DefaultTableModel(null, titulo);
        for (int i = 0; i < listaVeh.size(); i++) {
            Object row[] = {listaVeh.get(i).getPlaca(),
                listaVeh.get(i).getMarca(), 
                listaVeh.get(i).getModelo(),
                listaVeh.get(i).getTransmision(), 
                listaVeh.get(i).getCilindraje(),
                listaVeh.get(i).getFechaCompra()};
            model.addRow(row);
        }

        tblClientes.setModel(model);
        txtCantVehiculos.setText(String.valueOf(tblClientes.getRowCount()));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgGestionDeClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgGestionDeClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgGestionDeClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgGestionDeClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgGestionDeClientes dialog = new DlgGestionDeClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCantVehiculos;
    private javax.swing.JLabel lblMostrarClientes;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtCantVehiculos;
    private javax.swing.JTextField txtMostrarCliente;
    // End of variables declaration//GEN-END:variables
}
